---
title: "R_Workshop"
author: "Ian Handel"
date: "2018-04-04"
output: html_document
---

### Creating R 'objects' and storing numbers in them.

```{r}
# put 99 into an object called 'x' then show what's in 'x'
x <- 99
x

# add 1 to what's in x and show the answer
x + 1
x

# check what's in x
x

# put 53 into an object called 'age' then show what's in 'age'
age <- 53
age

# put what's in 'x' into 'age' and show what's in 'age
age  <- x
age

# put some numbers into 'nums' and show what's in 'nums'
nums <- c(5, 7, 11, 23, 99, 23, 1, 4, 4)
nums

# show the square root of each number in 'nums'
sqrt(nums)

# show the total of the numbers in 'nums'
sum(nums)

# show the arithemtic mean of what's in 'nums'
mean(nums)
```

### Try some other functions
```{r}
length(nums)
sort(nums)
rev(nums)
sample(nums)
sample(nums)
min(nums)
max(nums)
median(nums)
```

### Function arguments
```{r}
pi
round(pi)
round(pi, digits = 4)
round(pi, 4)
```


### other types of data
```{r}
eyes <- c("blue", "green", "blue", "brown")

happy <- c(TRUE, FALSE, TRUE, TRUE)

12 < 9

"ian" == "fred"
```



### Installing add-in packages
```
install.packages("tidyverse")
install.packages("skimr")
```

### Loading 'add-in' packages

```{r}
library(tidyverse) # to tidy, manipulate and explore data
```


### Rivers data
```{r}
rivers
?rivers
```

Find the length of the shortest and longest rivers.
How many rivers in this set?
Whats the mean (and median length)?

### Introducing the 'pipe'

```{r}
# put the square root of 'nums' into 'roots'
# then put the sum of that into sum_roots
roots <- sqrt(nums)
sum_roots1 <- sum(roots)
sum_roots1
```

```{r}
# do it all in one go
sum_roots2 <- sum(sqrt(nums))
sum_roots2
```


```{r}
# as above using the 'pipe'
sum_roots3 <- nums %>% sqrt() %>% sum()
sum_roots3
```







